### ISSUE TITLE
Display Antennas on Map

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/nycmesh-node-visualizer#20]
## Description
Use ```access_points.json``` to fetch the coordinates of each antenna. Use the coordinates to display the antennas on the map. You can use the ```<Circle /> ``` component to render the antenna. 

## Definition of Done
Create a component that renders the antennas on the map.

**Comment by ericzty** [comment]
Great progress so far, let's work on
* Making the dots smaller
* Making the dots not transparent
