### ISSUE TITLE
Create endpoint to fetch Antennas

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/nycmesh-node-visualizer#22]
## Description
Create an endpoint to fetch all the Antennas in the Postgres database. The endpoint should return an array of JSON nodes. For now, the JSON will have the following schema: ```name, modelName, frequency, displayName, location```

## Definition of Done
Setup an endpoint that queries the database and returns an array of all the antennas.

**Comment by Caposto** [comment]
Recommend abstracting the API call logic into a custom hook: https://www.makeuseof.com/react-build-custom-hook-api-calls/#:~:text=Creating%20a%20Custom%20React%20Hook&text=The%20hook%20should%20make%20the,receive%20responses%20over%20HTTP%20asynchronously. It separates the code nicely and is more "reactive"

**Comment by miguel-merlin** [comment]
You can use the database schema found in Discussion #30

**Comment by miguel-merlin** [comment]
@laddhasuneedhi High Priority
