### ISSUE TITLE
Local PostgreSQL Database with Docker

### ISSUE THREAD

**Issue by Caposto** [stevensblueprint/nycmesh-node-visualizer#32]
Could also be done with a script, but Docker seems like a good way to setup the antenna DB while we wait for the staging environments.

This is stolen from Ricky, but here is a **docker-compose.yaml** file that will initialize the database. You will need to add an **init.sql** file to create your tables and seed them with data as well, but then after that when you spin up the container everyone should be able to work with a local copy of the database instance:

`version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local`

Here are more resources:
https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
https://medium.com/@jewelski/quickly-set-up-a-local-postgres-database-using-docker-5098052a4726

**Comment by miguel-merlin** [comment]
@OwenTruong or @Arnavpmr?

**Comment by OwenTruong** [comment]
Hi, Arnav said he is going to work on that
